//! Embed the bundled agent skills into the binary.
//!
//! `think-and-ship skills install` writes these trees into a coding agent's
//! user-level skills directory. They have to travel *inside* the binary — the
//! common install path is `cargo install think-and-ship`, where no repo
//! checkout exists on the target machine — so this walks the two source trees
//! at build time and generates include_str!-backed tables:
//!
//! * `skills/<skill>/**`                  → `SKILL_FILES`        (the base bundle)
//! * `skill-clients/<client>/<skill>/**`  → `SKILL_CLIENT_FILES` (per-client overlay)
//!
//! Walking beats a hand-maintained list: adding a reference file to a skill
//! then needs no code change, and a skill that loses a file can't leave a
//! stale `include_str!` behind.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed=skills");
    println!("cargo:rerun-if-changed=skill-clients");

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str(&table(
        &manifest_dir.join("skills"),
        "SKILL_FILES",
        "Every bundled skill file as (path relative to `skills/`, contents).",
    ));
    out.push_str(&table(
        &manifest_dir.join("skill-clients"),
        "SKILL_CLIENT_FILES",
        "Per-client overlay files as (path relative to `skill-clients/`, contents), \
         i.e. `<client>/<skill>/<path within the skill>`.",
    ));

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("skill_files.rs");
    fs::write(&dest, out).expect("writing generated skill tables");
}

/// Render one `&[(&str, &str)]` table for every file under `root`.
fn table(root: &Path, name: &str, doc: &str) -> String {
    let mut files = Vec::new();
    collect(root, root, &mut files);
    files.sort();

    let mut out = format!("/// {doc}\npub static {name}: &[(&str, &str)] = &[\n");
    for (rel, abs) in &files {
        // Re-emit the changed-file trigger per entry so an edit to any skill
        // file (not just an add/remove) rebuilds the table.
        println!("cargo:rerun-if-changed={}", abs.display());
        // Debug-formatting the path string escapes Windows backslashes, so the
        // generated include_str! literal is valid on every platform.
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            rel,
            abs.display().to_string()
        ));
    }
    out.push_str("];\n");
    out
}

/// Depth-first walk collecting (slash-separated relative path, absolute path)
/// for every file under `dir`. Slashes are used regardless of platform so the
/// generated keys are stable; the installer re-joins them with `Path::join`.
/// Dotfiles are skipped — they are editor/OS residue, never part of a skill.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("walked path is under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().to_string())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path));
        }
    }
}
