//! `think-and-ship otel` — stand up a real telemetry stack and send the trace.
//!
//! # Why this exists
//!
//! [`crate::otel`] has been able to produce a valid OTLP body for a while, and
//! `trace export` writes it. Actually SEEING it required three hand-typed
//! commands from the README — a `docker run`, an export, and a `curl` — and the
//! first feedback you got was an empty Jaeger UI with no way to tell which of
//! the three had failed. That is a bad way to learn that your daemon is down.
//!
//! So this module owns the boring parts: generating a compose file, waiting for
//! the collector to actually listen, POSTing the body, and reading back what the
//! collector said. `trace export` is untouched and stays the pure, deterministic,
//! pipeable primitive; everything here builds on it.
//!
//! # Every verb stands alone
//!
//! [`up`], [`down`], [`send`] and [`status`] are independently runnable and
//! idempotent. The wizard chains them. A wizard that is the ONLY way to do the
//! thing is worse than the three commands it replaced — it cannot be scripted,
//! and it cannot be debugged a step at a time.
//!
//! # The headless rule
//!
//! A prompt that blocks a non-interactive session is a hang, and this project
//! has already paid for that lesson once on the MCP elicitation path. The
//! wizard therefore branches on [`std::io::IsTerminal`] BEFORE it asks anything:
//! with a terminal it prompts, with `--yes` it proceeds, and with neither it
//! prints the plan plus the exact non-interactive command and exits 0. Silently
//! answering "no" to every question — which is what the existing `confirm`
//! helper would do here — is not good enough: it produces a run that did
//! nothing and explained nothing.

use std::io::IsTerminal;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};

use crate::otlp_config::{HEADERS_ENV, configured_headers};

/// Jaeger's OTLP/HTTP receiver. `4317` is the gRPC twin; we speak HTTP because
/// that is what [`crate::otel`] emits.
pub const DEFAULT_OTLP_PORT: u16 = 4318;
/// Jaeger's UI, which is also its query API (`/api/traces`).
pub const DEFAULT_UI_PORT: u16 = 16686;
/// The compose project name, so `docker compose` finds our stack and not
/// whatever else the user has running.
const PROJECT_NAME: &str = "think-and-ship-otel";
const SERVICE_NAME: &str = "think-and-ship";

/// How long [`wait_ready`] gives the collector before giving up. A cold
/// `docker compose up` has to pull the image on first run, which is the slow
/// case this covers.
const READY_TIMEOUT: Duration = Duration::from_secs(120);

/// The generated stack.
///
/// # Why `COLLECTOR_OTLP_ENABLED` is set unconditionally
///
/// Jaeger 1.x (>= 1.35) speaks OTLP only when that variable is true; 2.x has it
/// on by default and ignores the variable. Setting it is load-bearing on one
/// and harmless on the other, so it goes in rather than making the user find
/// out which major version their tag resolved to.
///
/// # Why the image is pinned by MAJOR rather than `:latest`
///
/// `:latest` silently moved this stack across a major version once already in
/// the wild (1.x -> 2.x changed defaults). `:1` is a moving-but-bounded tag: it
/// picks up fixes without changing the contract this file was written against.
fn compose_yaml(otlp_port: u16, ui_port: u16) -> String {
    format!(
        "# Generated by `think-and-ship otel up`. Safe to edit, safe to delete —\n\
         # it is regenerated on demand and nothing else reads it.\n\
         services:\n\
         \x20 jaeger:\n\
         \x20   image: jaegertracing/all-in-one:1\n\
         \x20   container_name: {PROJECT_NAME}\n\
         \x20   environment:\n\
         \x20     # Required on Jaeger 1.x, default-on and ignored on 2.x.\n\
         \x20     - COLLECTOR_OTLP_ENABLED=true\n\
         \x20   ports:\n\
         \x20     - \"{ui_port}:16686\"   # UI + query API\n\
         \x20     - \"{otlp_port}:4318\"    # OTLP/HTTP — where the export is POSTed\n\
         \x20   restart: unless-stopped\n"
    )
}

/// Where the generated stack lives.
///
/// The data dir, NOT the user's repo: writing a compose file into someone's git
/// tree uninvited is how a tool gets uninstalled. `--dir` covers the case where
/// they want to commit and tweak it.
pub fn default_stack_dir() -> PathBuf {
    crate::infra::PersistenceConfig::from_env()
        .data_dir
        .join("otel-stack")
}

/// What `docker` can tell us right now. Separated from the actions so [`status`]
/// and the wizard can both report it without either running a container.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DockerState {
    /// No `docker` on PATH at all.
    NotInstalled,
    /// `docker` exists but the daemon is not answering — by far the most common
    /// first-run failure, and the one that must not surface as a raw error.
    DaemonDown,
    Ready,
}

impl DockerState {
    /// The sentence a human can act on. Kept next to the state so a caller
    /// cannot report a diagnosis without its remedy.
    pub fn advice(&self) -> &'static str {
        match self {
            Self::NotInstalled => {
                "docker is not on PATH. Install Docker Desktop (https://docs.docker.com/get-docker/) \
                 and run this again."
            }
            Self::DaemonDown => {
                "docker is installed but the daemon is not running. Start Docker Desktop (macOS: \
                 `open -a Docker`), wait for the whale icon to settle, then run this again."
            }
            Self::Ready => "docker is ready.",
        }
    }
}

/// Probe docker without starting anything.
pub fn docker_state() -> DockerState {
    match Command::new("docker").arg("info").output() {
        Err(_) => DockerState::NotInstalled,
        Ok(out) if out.status.success() => DockerState::Ready,
        Ok(_) => DockerState::DaemonDown,
    }
}

/// Write the compose file, creating the directory. Returns its path.
///
/// Idempotent by construction: the content is a pure function of the ports, so
/// rewriting it is a no-op unless the ports changed.
pub fn write_compose(dir: &Path, otlp_port: u16, ui_port: u16) -> Result<PathBuf> {
    std::fs::create_dir_all(dir)
        .with_context(|| format!("could not create the stack directory {}", dir.display()))?;
    let path = dir.join("docker-compose.yml");
    std::fs::write(&path, compose_yaml(otlp_port, ui_port))
        .with_context(|| format!("could not write {}", path.display()))?;
    Ok(path)
}

fn compose(dir: &Path) -> Command {
    let mut c = Command::new("docker");
    c.arg("compose")
        .arg("-p")
        .arg(PROJECT_NAME)
        .arg("-f")
        .arg(dir.join("docker-compose.yml"));
    c
}

/// Is the OTLP receiver actually accepting requests?
///
/// Asked of the collector rather than of docker: a container can be "up" while
/// the process inside it is still binding, and `docker compose up -d` returns
/// at the former. A send that races this is the failure mode this prevents.
pub fn endpoint_ready(otlp_port: u16) -> bool {
    std::net::TcpStream::connect_timeout(
        &([127, 0, 0, 1], otlp_port).into(),
        Duration::from_millis(500),
    )
    .is_ok()
}

/// Poll until the collector listens or `READY_TIMEOUT` elapses.
pub fn wait_ready(otlp_port: u16) -> bool {
    let deadline = Instant::now() + READY_TIMEOUT;
    while Instant::now() < deadline {
        if endpoint_ready(otlp_port) {
            return true;
        }
        std::thread::sleep(Duration::from_millis(400));
    }
    false
}

/// `otel up` — generate the compose file and start the stack.
pub fn up(dir: Option<&str>, otlp_port: u16, ui_port: u16) -> Result<()> {
    let state = docker_state();
    if state != DockerState::Ready {
        anyhow::bail!("{}", state.advice());
    }
    let dir = dir.map_or_else(default_stack_dir, PathBuf::from);
    let path = write_compose(&dir, otlp_port, ui_port)?;
    println!("stack file: {}", path.display());

    let out = compose(&dir)
        .args(["up", "-d"])
        .output()
        .context("could not run `docker compose up`")?;
    if !out.status.success() {
        anyhow::bail!(
            "`docker compose up -d` failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    print!("waiting for the collector on :{otlp_port} ");
    use std::io::Write;
    std::io::stdout().flush().ok();
    if wait_ready(otlp_port) {
        println!("— ready");
        println!("Jaeger UI: http://localhost:{ui_port}");
        println!("Next: `think-and-ship otel send` to push the current trace.");
        Ok(())
    } else {
        println!("— TIMED OUT");
        anyhow::bail!(
            "the collector did not start listening on :{otlp_port} within {}s. \
             Check `docker compose -p {PROJECT_NAME} logs`.",
            READY_TIMEOUT.as_secs()
        )
    }
}

/// `otel down` — stop the stack. Not an error if it was never up.
pub fn down(dir: Option<&str>) -> Result<()> {
    let dir = dir.map_or_else(default_stack_dir, PathBuf::from);
    if !dir.join("docker-compose.yml").exists() {
        println!("no stack to stop (nothing generated at {})", dir.display());
        return Ok(());
    }
    let out = compose(&dir)
        .arg("down")
        .output()
        .context("could not run `docker compose down`")?;
    if !out.status.success() {
        anyhow::bail!(
            "`docker compose down` failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    println!("stack stopped.");
    Ok(())
}

/// Wall-clock now, in the same unit the export's span timestamps use. Passed
/// into [`crate::otel::retention_note`] rather than read inside it so the
/// note's arithmetic stays a pure function of its inputs and can be tested at
/// a fixed instant.
fn now_nanos() -> u64 {
    u64::try_from(chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0)).unwrap_or(0)
}

/// The OTLP body for the current project, plus how many spans it carries and
/// whether it joined a caller's trace.
///
/// Deliberately reuses the same builder + validator `trace export` runs, so a
/// body that `send` transmits is byte-identical to one a user exported by hand.
pub fn current_export() -> Result<(serde_json::Value, usize, Option<String>)> {
    use crate::ship::engine::ShipEngine;
    use crate::think::engine::core::ReasoningServer;

    let project_id = crate::cli::resolve_project_id(None);
    let think =
        ReasoningServer::new_for_project(crate::cli::load_think_config(), project_id.clone());
    let ship = ShipEngine::new(project_id.clone()).with_persistence(
        crate::ship::persistence::Persistence::new(
            &crate::ship::persistence::PersistenceConfig::from_env(),
        ),
    );
    let inbound = crate::trace_context::load(&project_id);
    let export = crate::otel::build_otel(
        &project_id,
        ship.objective.as_ref().map(|o| (o, ship.tasks.as_slice())),
        think.all_steps(),
        inbound.as_ref(),
    );
    let problems = crate::otel::validate_otlp_with_external_parent(
        &export.body,
        inbound.as_ref().map(|c| c.parent_span_id.as_str()),
    );
    if !problems.is_empty() {
        anyhow::bail!(
            "export failed structural validation: {}",
            problems.join("; ")
        );
    }
    Ok((export.body, export.spans, inbound.map(|c| c.trace_id)))
}

/// What to say when an intake answers 401/403.
///
/// Takes header KEYS only, never the pairs. That is a deliberate signature: a
/// credential cannot leak into a log line through a function that was never
/// handed one.
fn auth_hint(sent_keys: &[String]) -> String {
    if sent_keys.is_empty() {
        format!(
            "\n  That status is about AUTHENTICATION, not about the trace body — this endpoint \
             wants a credential and none was sent.\
             \n  Set {HEADERS_ENV} (the OTLP exporter spec's own variable, `k=v` comma-separated):\
             \n    Honeycomb      {HEADERS_ENV}='x-honeycomb-team=<key>'\
             \n    Datadog        {HEADERS_ENV}='DD-API-KEY=<key>'\
             \n    Grafana Cloud  {HEADERS_ENV}='Authorization=Basic <base64 instance:token>'\
             \n  There is deliberately no --header flag: arguments are readable via `ps` and \
             land in shell history."
        )
    } else {
        format!(
            "\n  That status is about AUTHENTICATION, not about the trace body. {} header(s) \
             WERE sent ({}), so the value or the endpoint is wrong rather than the variable \
             being unset — check that the credential belongs to the account this URL serves \
             (most vendors are region-scoped).",
            sent_keys.len(),
            sent_keys.join(", ")
        )
    }
}

/// `otel send` — export and POST in one step, and say what came back.
///
/// Every failure mode gets a sentence a human can act on rather than a raw
/// transport error: an unreachable endpoint is the interesting case and it is
/// almost always "the stack is not up", so it says so.
///
/// Credentials for a hosted intake come from [`HEADERS_ENV`], not from a flag —
/// see that constant for why. The signature is therefore unchanged: reaching a
/// commercial backend costs zero new CLI surface.
pub fn send(endpoint: Option<&str>, otlp_port: u16) -> Result<()> {
    let endpoint = endpoint.map_or_else(
        || format!("http://localhost:{otlp_port}/v1/traces"),
        str::to_string,
    );
    let (body, spans, joined) = current_export()?;
    if spans == 0 {
        println!(
            "nothing to send: this project has no spans yet. Record some work first \
             (a ship objective, or think steps with timestamps)."
        );
        return Ok(());
    }
    // Parsed BEFORE the export is transmitted: a malformed credential list
    // should stop the run, not produce a 401 the user then debugs at the far
    // end.
    let headers = configured_headers()?;
    let header_keys: Vec<String> = headers.iter().map(|(k, _)| k.clone()).collect();

    // A repeat send is NOT refused — re-sending after recording more work is
    // the normal thing to do. But span ids are sha256-deterministic and OTLP
    // has no upsert, so the collector APPENDS: the old copies do not go away,
    // and three runs of a 587-span export read back as 1759 spans and four
    // roots. The operator has to be told that before they wonder
    // why their root appears N times.
    let project = crate::infra::resolve_project_id(None);
    let data_dir = crate::infra::PersistenceConfig::from_env().data_dir;
    if let Some(prior) = crate::otel_receipt::load(&data_dir, &project).last(&endpoint) {
        println!(
            "note: this project's trace was already sent to {endpoint} at {} ({} spans). \
             Span ids are deterministic and OTLP has no upsert, so those spans are still \
             there — the collector will hold each one twice.",
            prior.at, prior.spans
        );
    }

    // Retention is checked BEFORE the POST for the same reason the credential
    // list is: afterwards the operator is looking at a truthful 200 OK beside a
    // row count that disagrees with it, and nothing in that picture points at
    // the age of the data.
    if let Some(note) =
        crate::otel::retention_note(&body, now_nanos(), crate::otel::retention_bound_days())
    {
        println!("{note}");
    }

    // The async client behind a runtime, which is how every other outbound
    // call in `cli/` is made — adding reqwest's `blocking` feature for one
    // POST would pull a second HTTP stack into the binary.
    let runtime = tokio::runtime::Runtime::new()?;
    let (status, text) = runtime.block_on(async {
        let client = reqwest::Client::builder()
            .timeout(Duration::from_secs(10))
            .build()?;
        let mut request = client.post(&endpoint).json(&body);
        for (key, value) in &headers {
            request = request.header(key, value);
        }
        let response = match request.send().await {
            Ok(r) => r,
            Err(e) => {
                let hint = if e.is_connect() {
                    format!(
                        "\n  Nothing is listening at {endpoint}. Start the stack with \
                         `think-and-ship otel up`."
                    )
                } else {
                    String::new()
                };
                anyhow::bail!("could not POST the trace: {e}{hint}");
            }
        };
        let status = response.status();
        let text = response.text().await.unwrap_or_default();
        Ok::<_, anyhow::Error>((status, text))
    })?;
    if !status.is_success() {
        // 401/403 is categorically not about the trace. Reporting it the same
        // way as a 400 sends the reader to look at their span data, which is
        // the one place the problem is not.
        let hint = if matches!(status.as_u16(), 401 | 403) {
            auth_hint(&header_keys)
        } else {
            String::new()
        };
        anyhow::bail!(
            "the collector rejected the trace ({status}): {}{hint}",
            text.trim()
        );
    }
    // Recorded only on success, and a failure to record is not a failure to
    // send: this stamp is read by humans and nothing branches on it, so losing
    // it costs one pessimistic line of `otel status` and nothing else.
    let _ = crate::otel_receipt::record(
        &data_dir,
        &project,
        &endpoint,
        &crate::otel_receipt::SendReceipt {
            at: chrono::Utc::now().to_rfc3339(),
            spans,
            trace_id: joined
                .clone()
                .unwrap_or_else(|| crate::otel::trace_id(&project)),
        },
    );
    println!("sent {spans} spans to {endpoint} ({status})");
    if let Some(trace) = &joined {
        println!("joined the caller's trace {trace} (SEP-414)");
    }
    println!("Open http://localhost:{DEFAULT_UI_PORT} and pick the \"{SERVICE_NAME}\" service.");
    Ok(())
}

/// `otel status` — answer every question a failing send would raise, without
/// sending anything.
pub fn status(dir: Option<&str>, otlp_port: u16, ui_port: u16) -> Result<()> {
    let dir = dir.map_or_else(default_stack_dir, PathBuf::from);
    let state = docker_state();
    println!("docker:     {}", state.advice());
    println!(
        "stack file: {}",
        if dir.join("docker-compose.yml").exists() {
            dir.join("docker-compose.yml").display().to_string()
        } else {
            "not generated yet (`think-and-ship otel up` writes it)".into()
        }
    );
    println!(
        "collector:  {}",
        if endpoint_ready(otlp_port) {
            format!("listening on :{otlp_port} — UI at http://localhost:{ui_port}")
        } else {
            format!("not listening on :{otlp_port}")
        }
    );
    // The LIVE lane's only diagnostic surface. It cannot log — its stderr
    // belongs to the MCP stdio transport — so "is it on, and where is it
    // pointed" has to be answerable from here or not at all.
    println!(
        "live:       {}",
        crate::otlp_config::configured_endpoint().map_or_else(
            || format!(
                "off — the server emits spans only when {} (or {}) is set",
                crate::otlp_config::ENDPOINT_ENV,
                crate::otlp_config::TRACES_ENDPOINT_ENV
            ),
            |e| format!("on — the MCP server POSTs tool-call spans to {e} as calls happen"),
        )
    );
    // Keys only. The whole point of this line is to answer "did my variable
    // reach the command?" without ever putting a credential on a terminal that
    // people screenshot into issue reports.
    println!(
        "auth:       {}",
        match configured_headers() {
            Ok(h) if h.is_empty() => format!(
                "no OTLP headers set — fine for the local stack, rejected by every hosted \
                 intake (set {HEADERS_ENV})"
            ),
            Ok(h) => format!(
                "{} header(s) from the environment: {}",
                h.len(),
                h.iter()
                    .map(|(k, _)| k.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Err(e) => format!("{e}"),
        }
    );
    match current_export() {
        Ok((body, spans, joined)) => {
            println!("to send:    {spans} spans");
            // `otel status` exists to answer every question a failing send
            // would raise without sending — and a send that silently stores
            // two thirds of what it reported is exactly such a failure.
            if let Some(note) =
                crate::otel::retention_note(&body, now_nanos(), crate::otel::retention_bound_days())
            {
                println!("retention:  {note}");
            }
            let project = crate::infra::resolve_project_id(None);
            let receipts = crate::otel_receipt::load(
                &crate::infra::PersistenceConfig::from_env().data_dir,
                &project,
            );
            println!(
                "caller ctx: {}",
                caller_ctx_line(joined.as_deref(), &receipts)
            );
            println!(
                "exported:   {}",
                receipts.ever_sent().map_or_else(
                    || "never — this project's trace is not in any backend yet".to_string(),
                    |(endpoint, r)| format!("{} → {endpoint} ({} spans)", r.at, r.spans),
                )
            );
        }
        Err(e) => println!("to send:    export is not currently valid: {e}"),
    }
    Ok(())
}

/// The caller-context line, which is the one place the SEVERED-TREE state is
/// visible at all.
///
/// Held apart from [`status`] so the four states can be asserted without a
/// docker daemon, a collector or a data directory.
///
/// The interesting state is "adopted, never exported". From the moment a
/// context is adopted, every outbound tracker and cloud request carries a
/// `traceparent` naming a workspace span that exists only once an export lands.
/// Read back from Jaeger, the downstream leg detaches into a SECOND ROOT — two
/// disconnected fragments where there was one causal chain. The
/// line names that CONSEQUENCE rather than the internal state, because "a
/// context is adopted" is not a thing anyone can act on.
fn caller_ctx_line(joined: Option<&str>, receipts: &crate::otel_receipt::SendReceipts) -> String {
    let Some(trace) = joined else {
        return "none adopted — the export will mint its own trace id".into();
    };
    match receipts.ever_sent() {
        None => format!(
            "joined trace {trace} (SEP-414) — BUT NOTHING HAS BEEN EXPORTED YET. Until you run \
             `think-and-ship otel send` (or configure live emission), our outbound requests name \
             a span that does not exist, and the caller's tree shows those legs as a SEPARATE \
             ROOT rather than under us. Nothing errors: the collector answers 200 and the UI \
             renders."
        ),
        Some((endpoint, r)) => format!(
            "joined trace {trace} (SEP-414) — last exported {} to {endpoint}",
            r.at
        ),
    }
}

/// One wizard step: what it is called, and what running it non-interactively
/// would look like. Held as data so the headless branch can PRINT the plan it
/// would have run rather than guessing at it in a separate code path that could
/// drift from the real one.
struct Step {
    describe: &'static str,
    command: &'static str,
}

const PLAN: &[Step] = &[
    Step {
        describe: "Generate a docker-compose file for a local Jaeger and start it",
        command: "think-and-ship otel up",
    },
    Step {
        describe: "Export this project's trace and POST it to the collector",
        command: "think-and-ship otel send",
    },
];

fn ask(question: &str) -> bool {
    use std::io::{BufRead, Write};
    eprint!("{question} [Y/n] ");
    std::io::stderr().flush().ok();
    let mut line = String::new();
    match std::io::stdin().lock().read_line(&mut line) {
        Err(_) => false,
        // EOF — zero bytes, no newline. NOT the same as a human pressing
        // return, and the difference is load-bearing: `wizard < /dev/null`
        // reads EOF on every question, so a bare default-to-yes would run the
        // whole flow unattended. Found by deliberately removing the non-TTY
        // guard: that is exactly what happened — it started containers and
        // POSTed without anyone answering anything.
        Ok(0) => false,
        Ok(_) => {
            // Defaults to yes: every step is reversible (`otel down`) and the
            // user typed `wizard` to get exactly this.
            matches!(line.trim().to_ascii_lowercase().as_str(), "" | "y" | "yes")
        }
    }
}

/// `otel wizard` — the guided flow, and the whole point of the command.
///
/// Three behaviours, none of which can block:
/// - a terminal: prompt per step, defaulting to yes;
/// - `--yes`: run every step without asking;
/// - neither (a pipe, CI, an agent's shell): print the plan and the exact
///   commands, then exit 0.
pub fn wizard(dir: Option<&str>, otlp_port: u16, ui_port: u16, yes: bool) -> Result<()> {
    let interactive = std::io::stdin().is_terminal();
    println!("think-and-ship OpenTelemetry setup");
    println!("  collector: local Jaeger all-in-one (docker compose)");
    println!("  OTLP/HTTP: :{otlp_port}    UI: http://localhost:{ui_port}");
    println!(
        "  stack dir: {}",
        dir.map_or_else(|| default_stack_dir().display().to_string(), str::to_string)
    );
    println!();

    if !interactive && !yes {
        println!("Not a terminal, so nothing will be run and nothing was changed.");
        println!("This is what the wizard would do:");
        for (i, step) in PLAN.iter().enumerate() {
            println!("  {}. {}\n     $ {}", i + 1, step.describe, step.command);
        }
        println!("\nRun it without prompts:  think-and-ship otel wizard --yes");
        return Ok(());
    }

    let state = docker_state();
    if state != DockerState::Ready {
        // Reported rather than raised: the user asked for guidance, and a
        // stack trace is not guidance.
        println!("Cannot continue — {}", state.advice());
        return Ok(());
    }

    if yes || ask(&format!("{}?", PLAN[0].describe)) {
        up(dir, otlp_port, ui_port)?;
    } else {
        println!("Skipped. Nothing is running, so there is nowhere to send.");
        return Ok(());
    }
    println!();
    if yes || ask(&format!("{}?", PLAN[1].describe)) {
        send(None, otlp_port)?;
    }
    println!();
    println!("Done. `think-and-ship otel status` re-checks all of this,");
    println!("and `think-and-ship otel down` stops the stack.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The one thing about the generated compose that is not cosmetic: Jaeger
    /// 1.x is silent about OTLP without it, so a stack generated without this
    /// line accepts nothing and gives no reason.
    #[test]
    fn compose_enables_otlp_for_jaeger_1x() {
        let yaml = compose_yaml(4318, 16686);
        assert!(
            yaml.contains("COLLECTOR_OTLP_ENABLED=true"),
            "Jaeger 1.x drops OTLP silently without this"
        );
    }

    /// Ports are what a user overrides when 4318 is already taken, so both must
    /// reach the mapping rather than only the comment.
    #[test]
    fn compose_maps_the_requested_ports() {
        let yaml = compose_yaml(14318, 26686);
        assert!(yaml.contains("\"14318:4318\""), "OTLP port must be mapped");
        assert!(yaml.contains("\"26686:16686\""), "UI port must be mapped");
        // The container side is fixed — remapping it would break Jaeger.
        assert!(!yaml.contains("14318:14318"));
    }

    /// Pinned by major on purpose; `:latest` crossed a major version in the
    /// wild and changed the OTLP defaults underneath users.
    #[test]
    fn compose_pins_the_image_major() {
        assert!(compose_yaml(4318, 16686).contains("jaegertracing/all-in-one:1"));
        assert!(!compose_yaml(4318, 16686).contains(":latest"));
    }

    /// Writing is idempotent: same ports, same bytes. `otel up` twice must not
    /// be an error, and this is the half of that promise that is ours.
    #[test]
    fn writing_the_compose_twice_is_a_no_op() {
        let dir = tempfile::tempdir().expect("tempdir");
        let a = write_compose(dir.path(), 4318, 16686).expect("first write");
        let first = std::fs::read_to_string(&a).expect("read");
        let b = write_compose(dir.path(), 4318, 16686).expect("second write");
        assert_eq!(a, b);
        assert_eq!(first, std::fs::read_to_string(&b).expect("read"));
    }

    /// Every FAILING diagnosis ships with a remedy, because a state that tells
    /// you something is wrong without telling you what to do is the thing this
    /// module exists to replace.
    ///
    /// `Ready` is deliberately exempt and the first version of this test got
    /// that wrong: it asserted a blanket length floor, and "docker is ready."
    /// — which has no action because there is nothing to fix — failed it. The
    /// assertion now says what was actually meant.
    #[test]
    fn every_failing_docker_state_advises_an_action() {
        for state in [DockerState::NotInstalled, DockerState::DaemonDown] {
            let advice = state.advice();
            assert!(
                advice.contains("run this again"),
                "a failing state must tell the user what to do next: {advice}"
            );
        }
        assert!(DockerState::DaemonDown.advice().contains("open -a Docker"));
        assert!(DockerState::NotInstalled.advice().contains("docker.com"));
        // Ready says so plainly and prescribes nothing.
        assert!(!DockerState::Ready.advice().is_empty());
        assert!(!DockerState::Ready.advice().contains("run this again"));
    }

    /// The plan the headless branch prints must be the commands that actually
    /// exist, not a hand-maintained duplicate that drifts.
    #[test]
    fn the_printed_plan_names_real_commands() {
        assert_eq!(PLAN.len(), 2);
        for step in PLAN {
            assert!(
                step.command.starts_with("think-and-ship otel "),
                "step must name a real otel verb: {}",
                step.command
            );
        }
    }

    /// A port nothing is bound to must read as not-ready. Port 1 is reserved
    /// and unbindable without privileges, so this cannot flake on a busy box.
    #[test]
    fn a_dead_port_is_not_ready() {
        assert!(!endpoint_ready(1));
    }

    /// The whole point of the line: "adopted but never exported" must not read
    /// like "adopted". It has to name what the BACKEND shows — a separate root
    /// — because that is the only fact an operator can act on, and because
    /// nothing else anywhere reports it (200 from the collector, a rendered UI,
    /// and a clock-skew warning that is about timing math).
    #[test]
    fn an_adopted_but_unexported_context_names_the_second_root() {
        let line = caller_ctx_line(
            Some("abc123"),
            &crate::otel_receipt::SendReceipts::default(),
        );
        assert!(line.contains("abc123"), "{line}");
        assert!(
            line.contains("SEPARATE ROOT"),
            "must name the consequence: {line}"
        );
        assert!(line.contains("otel send"), "must name the remedy: {line}");
        // And it must not read like the healthy case.
        assert!(line.contains("NOTHING HAS BEEN EXPORTED"), "{line}");
    }

    /// Once an export has landed the warning must GO AWAY, or it becomes noise
    /// the reader learns to skip — and then it is worth nothing on the day it
    /// matters.
    #[test]
    fn an_exported_context_reports_when_and_stops_warning() {
        let mut receipts = crate::otel_receipt::SendReceipts::default();
        receipts.by_endpoint.insert(
            "http://localhost:4318/v1/traces".into(),
            crate::otel_receipt::SendReceipt {
                at: "2026-07-28T12:00:00Z".into(),
                spans: 587,
                trace_id: "abc123".into(),
            },
        );
        let line = caller_ctx_line(Some("abc123"), &receipts);
        assert!(line.contains("2026-07-28T12:00:00Z"), "{line}");
        assert!(line.contains("localhost:4318"), "{line}");
        assert!(
            !line.contains("SEPARATE ROOT"),
            "warning must clear: {line}"
        );
    }

    /// No caller context is not a problem and must not be dressed as one — the
    /// export simply mints its own trace id, which is the ordinary case.
    #[test]
    fn no_caller_context_is_reported_without_alarm() {
        let line = caller_ctx_line(None, &crate::otel_receipt::SendReceipts::default());
        assert!(line.contains("none adopted"), "{line}");
        assert!(!line.contains("SEPARATE ROOT"), "{line}");
    }

    /// The chunk's actual ask: a 401 must send the reader to their credential,
    /// not to their span data. Both branches must name AUTH and the variable.
    #[test]
    fn a_401_hint_names_auth_and_the_variable() {
        let unset = auth_hint(&[]);
        assert!(unset.contains("AUTHENTICATION"), "{unset}");
        assert!(unset.contains(HEADERS_ENV), "{unset}");
        assert!(unset.contains("x-honeycomb-team"), "must show an example");

        let set = auth_hint(&["x-honeycomb-team".to_string()]);
        assert!(set.contains("AUTHENTICATION"), "{set}");
        // The two cases need different next moves, so they must not read alike.
        assert!(set.contains("WERE sent"), "{set}");
        assert!(
            !set.contains("none was sent"),
            "a sent-but-rejected credential is a different problem: {set}"
        );
    }

    /// `auth_hint` takes keys, never pairs, so a credential VALUE cannot reach
    /// a terminal through it. This pins that signature against a future
    /// refactor that "helpfully" passes the whole map.
    #[test]
    fn the_auth_hint_cannot_print_a_secret() {
        let hint = auth_hint(&["x-honeycomb-team".to_string(), "DD-API-KEY".to_string()]);
        assert!(hint.contains("x-honeycomb-team"));
        assert!(
            !hint.contains("hunter2"),
            "values are not in scope for this function by construction"
        );
        // The parsed value exists here and is provably absent from the message.
        let parsed =
            crate::otlp_config::parse_otlp_headers(HEADERS_ENV, "x-honeycomb-team=hunter2")
                .expect("parse");
        assert_eq!(parsed[0].1, "hunter2");
        assert!(!hint.contains(&parsed[0].1));
    }
}
